### ISSUE TITLE
Totally remove onRemoteChange

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#121]
I don't really understand the reason of removing it TBH, but it's been deprecated for at least three months. Should I remove it and keep `patch-applied` event only in Palindrome 3.0.0?

cc @tomalec @warpech

**Comment by warpech** [comment]
We want people to upgrade to Palindrom 3.0.0 without really noticing it, so I would try to keep as much backwards compatibility as possible. 

I would prefer us to remove deprecated features when things get stable, maybe few months from now.

**Comment by warpech** [comment]
Rationale: adapting to it is not easy for our users, because their apps would not fail instantly.

**Comment by warpech** [comment]
I have looked into it and yes, `onRemoteChange` is deprecated since 2.0.0 (https://github.com/Palindrom/Palindrom/commit/f36b534fd4c6f5a2aff71bf5a4dc3f8a314b0e13).

@joozek78 do you remember the exact reason?

The spirit of that deprecation was to go towards DOM Events way. But maybe that was wrong? Palindrom is not DOM-aware, therefore it needs to mock EventEmitter. Maybe we should simplify that once again and only have callbacks in Palindrom.

PalindromDom is DOM-aware and it can trigger events.

**Comment by joozek78** [comment]
I think the reason was simply not to duplicate the functionality of events

**Comment by alshakero** [comment]
I'd really like it if we got rid of the EventEmitter. It's needless except for this `patch-applied`.

**Comment by joozek78** [comment]
![image](https://cloud.githubusercontent.com/assets/6013217/24205241/1f25d3ca-0f1b-11e7-8e00-c737b1bf6c5a.png)

**Comment by alshakero** [comment]
@joozek78 haha, I just come from the principle that the best code is no code. The more you remove code the better the quality. Given no feature is sacrificed.

**Comment by joozek78** [comment]
I agree, if you only removed code and didn't break anything, then your
change is (most probably) pure goodness

**Comment by warpech** [comment]
I think that `starcounter-debug-aid` might be listening to the events emitted by Palindrom.

We would need to change that somehow (maybe emit the events from PalindromDom)?

**Comment by alshakero** [comment]
There is no big difference, but that would be definetly cleaner.

**Comment by warpech** [comment]
Actually emitting the events from PalindromDom does not fix the bad design that we have (introduced by me, I admit). Plain JS objects cannot trigger DOM events, which is why the lines https://github.com/Palindrom/Palindrom/blob/37aef7730cc17ce3f630782032381905f467d96f/src/palindrom.js#L23-L85 are used.

I would be very happy to remove that and stick to callbacks.

**Comment by alshakero** [comment]
Closing as settled to removing events and sticking to callbacks.

As for `starcounter-debug-aid`, it won't be affected at all. Because it [uses `palindrom-polymer-client` events](https://github.com/Starcounter/starcounter-debug-aid/blob/master/src/puppet-js-listener.js#L80-L128). Not PalindromDOM's.
