### ISSUE TITLE
Deperecate `ignoreAdd` then remove it

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#136]
Due to the buggy behaviour and avoidable use cases,  `ignoreAdd` will be removed from Palindrom 3.0.0.

As for the next PuppetJS 2.5. `ignoreAdd` will warn every time it is accessed. And will also warn everytime a value is actually ignored in runtime.

This will allow developers to track every usage and remove it gradually before Palindrom 3.0.0 is shipped.

/cc @warpech  @tomalec

**Comment by warpech** [comment]
To make sure that `ignoreAdd` functionality can be achieved on Polymer level, provide https://github.com/StarcounterApps/KitchenSink/issues/135 that does not trigger warnings in PuppetJS 2.5

**Comment by warpech** [comment]
I was quite surprised to see that after releasing Puppet 2.5.0, the warning `puppet.js:585 Puppet: ignoreAdd is deprecated and will be removed soon.` started to appear in all Starcounter apps.

Turns out that `ignoreAdd` is enabled by default in `palindrom-client`: https://github.com/Palindrom/palindrom-polymer-client/blob/04716b9620bd0f7786a23e356e3634aa702508f7/palindrom-client.html#L79

Luckily, PuppetJs shows a different warning when `ignoreAdd` is actually used. That is the warning where the devs should put a lot of attention.

![2017-06-20 21_52_57-kitchensink](https://user-images.githubusercontent.com/566463/27352986-d76be5d6-5602-11e7-9a2f-d8d0d86efb6f.png)

**Comment by alshakero** [comment]
Should I patch the current `palindrom-client` for the meantime?

**Comment by warpech** [comment]
I don't think this is necessary, since:

> PuppetJs shows a different warning when ignoreAdd is actually used. That is the warning where the devs should put a lot of attention.

Or do you think patching `palindrom-client` should give any improvement for the developer's experience?

**Comment by alshakero** [comment]
@warpech well yes, current warning is crying wolf :(

**Comment by alshakero** [comment]
@warpech but I agree. Those who don't use it won't care, and the ones that do will take notice :D

**Comment by warpech** [comment]
This issue seems done, can it be closed?

**Comment by alshakero** [comment]
Yes sir it can. Closing as done in https://github.com/Palindrom/Palindrom/pull/138.
