### ISSUE TITLE
Cover eventual consistency in tests

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#147]

**Comment by warpech** [comment]
First test that tests this was added in https://github.com/Palindrom/Palindrom/pull/159/commits/9bc324d0497029fc71b7a03667b1d4377d29cb99

**Comment by warpech** [comment]
@alshakero reports that this can be closed because it was fixed with other fixes. We have about 2 tests that check for eventual consistency and it is hard to define what else should be done now. Closing as done.

If possible, @alshakero please add more details about how it is solved.

In future, we will most probably add new tests as we work on reconnection.

**Comment by alshakero** [comment]
> If possible, @alshakero please add more details about how it is solved.

Well we never had any issues with OT until https://github.com/Palindrom/Palindrom/issues/157, which we had added tests for. Other than that we'll have to create the need for the tests then add them for that need created from thin air. Especially these the OT stack is rarely maintained to need tests to cover it during maintenance.
