### ISSUE TITLE
⏰ Palindrom does not apply OT correctly

### ISSUE THREAD

**Issue by warpech** [Palindrom/Palindrom#157]
# Steps to reproduce

The same as in #156 

To make it easier, I have created a test suite with real data: https://github.com/Palindrom/Palindrom/commit/9bc324d0497029fc71b7a03667b1d4377d29cb99. The one failing test is the one that shows the problem.

# Expected

Palindrom should correctly apply patches that come out of order. 

# Actual

In this particular case, the XHR handler on the server triggers a WS push, which is delivered to the client before XHR. 

The client gets server version 2 through WS, then 1 through XHR, then 3 through WS. 

If the OT worked correctly, that should not be a problem. But it seems that the client applies the patches from the OT queue on a outdated version of the `obj`.

This is essencially the problem that causes https://github.com/Starcounter/inside.starcounter.com/issues/23. This was very hard to debug because of how Palindrom hides incoming patch exceptions in Promise `catch`.

**Comment by alshakero** [comment]
> To make it easier, I have created a test suite with real data: 9bc324d

This is beyond considerate. Thank you so much.

> This was very hard to debug because of how Palindrom hides incoming patch exceptions in Promise catch

I fixed this in Palindrom `master` before I left but it was a small issue to release. Next release will log the errors.

**Comment by alshakero** [comment]
So after some investigation on this, I can say it is not _cleanly_ possible without server modifications. Because current server scenario is:

1- Send a **full** object via XHR (eg: `{name: 'George'}`).
2- Send **patches** to that object via WS or HTTP PATCH (eg: `[{op: "replace", path: "/path", value: "new Value"}]`).

Understandably enough, these are not interchangeable.

We can cache 2 and wait for 1 but IMHO all this complexity is redundant and can be fixed from the server in a much cleaner and future-friendly manner. I suggest that the server never sends full objects anymore, only patches, such that first patch becomes:
```js
[{op: replace, path: "", value: {key: value}}]
```

And this will make HTTP GET + HTTP PATCH + WS messages equivalent and all fall under OT. Also, this will allow us to get rid of initial HTTP request that is slowing us ~500ms down.
