### ISSUE TITLE
Handle non-JSON WebSocket messages as reasons for errors

### ISSUE THREAD

**Issue by alshakero** [Palindrom/Palindrom#188]
And take proper actions with them (log or failover to HTTP etc..). I'll comment here what once I formulate how to handle them. Please comment if you have any ideas.

Related: https://github.com/Starcounter/Home/issues/174#issuecomment-342473427

Comment on https://github.com/Starcounter/Home/issues/174, https://github.com/Starcounter/Home/issues/340 when done.

**Comment by warpech** [comment]
As explained in Starcounter/Home#174 (comment), Palindrom will try to parse any WebSocket message as JSON. If the message does not parse as JSON (for example because it is a stack trace text), this is considered a fatal error end the text that did not parse will be logged as error in the browser console.

**Comment by warpech** [comment]
As explained in https://github.com/Starcounter/Home/issues/174#issuecomment-342473427:

> Sorry for the last now-deleted comment, I misread. Maybe we can send a normal string error from the server. And in Palindrom we can simply `try` before `JSON.parse` and throw the raw message in `catch` and that's it. Without any protocol changes.

Palindrom will try to parse any WebSocket message as JSON. If the message does not parse as JSON (for example because it is a stack trace text), this is considered a fatal error end the text that did not parse will be logged as error in the browser console.

**Comment by warpech** [comment]
Level1 part is done: https://github.com/Starcounter/Home/issues/340

**Comment by alshakero** [comment]
PR in https://github.com/Palindrom/Palindrom/pull/191
